version: '3.4'
services:
  mariadb:
    image: mariadb:10.2
    restart: on-failure
    networks: 
      - backend
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mybb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mybb
      MYSQL_USER: mybb
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme

volumes:
  mybb:
networks:
  backend:
